# --- !Ups

create table PRODUCT ("ID" INT PRIMARY KEY NOT NULL, "CATEGORY_ID" INT NOT NULL, "NAME" VARCHAR NOT NULL, "DESCRIPTION" TEXT NOT NULL, "PRICE" INT NOT NULL);
create table CATEGORY ("ID" INT PRIMARY KEY NOT NULL,  "NAME" VARCHAR NOT NULL, "DESCRIPTION" TEXT NOT NULL);

# --- !Downs

DROP TABLE PRODUCT;
DROP TABLE CATEGORY;